# Generated by Django 5.2.7 on 2025-10-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_files', '0002_rename_title_category_name_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(),
        ),
    ]
